# Site settings
title: Dr. Krishnakanta Mondal
email: krishnakanta.mondal@cup.edu.in
description: Academic webpage of Dr. Krishnakanta Mondal
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics: 
google_analytics_4: 
google_tag_manager: 

# Footer info
affiliation: >
    Dr. Krishnakanta Mondal<br/>
    DST-INSPIRE Faculty<br/>
    <a href="http://www.cup.edu.in/centre_phy_sci.php" target="_blank">Department of Physics</a><br/>
    Central University of Punjab

location: >
  <a href="http://mme-428.ga/" target="_blank">Materials Modelling Lab (428)</a><br/>
  Central University of Punjab <br/>
  Bathinda, VPO Ghudda<br/>
  Punjab, India 151401

contact: >
    <a href="mailto:krishnakanta.mondal@cup.edu.in" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Dr. Krishnakanta Mondal via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> About this website </a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: posts
  - name: research
  - name: teaching
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Mondal
  first_name: [Krishnakanta]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
